export const points = [
    {
        child_tsumo_from_child: 300,
        child_tsumo_from_parent: 500,
        child_ron: 1000,
        parent_tsumo: 500,
        parent_ron: 1500,
        aka: "30符1翻",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.2
    },
    {
        child_tsumo_from_child: 400,
        child_tsumo_from_parent: 700,
        child_ron: 1500,
        parent_tsumo: 700,
        parent_ron: 2100,
        aka: "20符1翻",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.2
    },
    {
        child_tsumo_from_child: 400,
        child_tsumo_from_parent: 800,
        child_ron: 1600,
        parent_tsumo: 800,
        parent_ron: 2400,
        aka: "テンパネ？",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.01
    },
    {
        child_tsumo_from_child: 700,
        child_tsumo_from_parent: 1300,
        child_ron: 2700,
        parent_tsumo: 1300,
        parent_ron: 3900,
        aka: "25符",
        ex1: "七対子",
        ex2: "",
        ex3: "",
        rate: 0.1
    },
    {
        child_tsumo_from_child: 1000,
        child_tsumo_from_parent: 2000,
        child_ron: 4000,
        parent_tsumo: 2000,
        parent_ron: 4000,
        aka: "30符3翻",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.2
    },
    {
        child_tsumo_from_child: 1300,
        child_tsumo_from_parent: 2600,
        child_ron: 5200,
        parent_tsumo: 3000,
        parent_ron: 2000,
        aka: "リーチ",
        ex1: "平和ツモ",
        ex2: "",
        ex3: "",
        rate: 0.4
    },
    {
        child_tsumo_from_child: 1600,
        child_tsumo_from_parent: 3200,
        child_ron: 6400,
        parent_tsumo: 3200,
        parent_ron: 9600,
        aka: "",
        ex1: "",
        ex2: "七対子",
        ex3: "",
        rate: 0.4
    },
    {
        child_tsumo_from_child: 2000,
        child_tsumo_from_parent: 3900,
        child_ron: 7700,
        parent_tsumo: 3900,
        parent_ron: 11600,
        aka: "30符4翻",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.4
    },
    {
        child_tsumo_from_child: 2000,
        child_tsumo_from_parent: 4000,
        child_ron: 8000,
        parent_tsumo: 4000,
        parent_ron: 12000,
        aka: "満貫",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.4
    },
    {
        child_tsumo_from_child: 3000,
        child_tsumo_from_parent: 6000,
        child_ron: 12000,
        parent_tsumo: 6000,
        parent_ron: 18000,
        aka: "跳満",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.2
    },
    {
        child_tsumo_from_child: 4000,
        child_tsumo_from_parent: 8000,
        child_ron: 16000,
        parent_tsumo: 8000,
        parent_ron: 24000,
        aka: "倍満",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.1
    },
    {
        child_tsumo_from_child: 6000,
        child_tsumo_from_parent: 12000,
        child_ron: 24000,
        parent_tsumo: 12000,
        parent_ron: 36000,
        aka: "三倍満",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.01
    },
    {
        child_tsumo_from_child: 8000,
        child_tsumo_from_parent: 16000,
        child_ron: 32000,
        parent_tsumo: 16000,
        parent_ron: 48000,
        aka: "数え役満",
        ex1: "",
        ex2: "",
        ex3: "",
        rate: 0.02
    },
]